### ISSUE TITLE
Create custom get by id function

### ISSUE THREAD

**Issue by kburk1997** [kburk1997/yacs-admin#2]
Right now, activeresource's GET format for an object with id ```<id>``` is:
```
.../courses/<id>.json
```

Yet YACS's format is:

```
/api/v5/courses.json?id=<id>
```

This makes the show view a lot more complicated than thought.

Create a custom function to get around this in the show function

**Comment by Bad-Science** [comment]
@kburk1997 I am currently adding support for .../courses/<id>.json. Assume that all standard restful routes will be available :)

**Comment by kburk1997** [comment]
@Bad-Science thanks so much!
